name: Example CMake

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        fail-fast: false
        include:
          - { icon: '⬛', sys: mingw32, env: i686 }
          - { icon: '🟦', sys: mingw64, env: x86_64 }
          - { icon: '🟨', sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
          - { icon: '🟧', sys: clang64, env: clang-x86_64 } # Experimental!
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja

    - name: '🚧 Build TOOL'
      run: |
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
