name: Tool

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  matrix:
    name: ⬜ Generate list of jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.matrix.outputs.jobs }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - id: matrix
      uses: ./matrix
      with:
        systems: >-
          mingw32
          mingw64
          ucrt64
          clang64
          clangarm64

  msys2:
    needs: matrix
    uses: ./.github/workflows/PKGBUILD.yml
    with:
      name: TOOL
      matrix: ${{ needs.matrix.outputs.jobs }}
      path: examples/pkgbuild
      test: |
        uname -a
        which TOOL
        TOOL
